### ISSUE TITLE
When i used face-find.py ,i meet some problem

### ISSUE THREAD

**Issue by anthonyyuan** [vearutop/face-postgre#4]
python3 face-find.py 1.jpg
Found 1 faces in the image file 1.jpg
- Face #0 found at Left: 180 Top: 263 Right: 366 Bottom: 449
Traceback (most recent call last):
  File "face-find.py", line 47, in <module>
    dd=db.query(query)
  File "/usr/local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 1231, in __call__
    return self._prepare(query)(*parameters)
  File "/usr/local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2331, in prepare
    ps._fini()
  File "/usr/local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 1513, in _fini
    self.database._pq_complete()
  File "/usr/local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2609, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "/usr/local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "/usr/local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 532, in raise_server_error
    raise server_error
postgresql.exceptions.SyntaxError: syntax error at or near ")"
  CODE: 42601
  LOCATION: File 'scan.l', line 1087, in scanner_yyerror from SERVER

**Comment by Kinani** [comment]
Anything on this? I have the same error with `face-find.py`.
seems like `db.execute(query)` is working fine while `db.query(query)` throws the error.
